[package]
name = "swift-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
swift-bridge-macro = {path = "crates/swift-bridge-macro"}

[workspace]
members = [
  "crates/swift-bridge-macro",
  "crates/swift-bridge-build",
  "crates/swift-bridge-ir",
  "crates/swift-integration-tests"
]
