[book]
authors = ["Chinedu Francis Nwafili"]
language = "en"
multilingual = false
src = "src"
title = "The swift-bridge Book"

[output.html]
git-repository-url = "https://github.com/chinedufn/swift-bridge"
